"""Render docs/UNCERTAINTY_SURVIVAL.md from out/uq_survival.json.

Every number below is formatted from the measured results. Sentences that make a
comparison pick their wording from the numbers, so a rerun that flips a result
flips the sentence rather than leaving a stale claim behind.
"""
from __future__ import annotations

import numpy as np

NAMES = {
    "gbm_failed_only": "GBM, drop running engines",
    "gbm_naive": "GBM, treat running engines as failed",
    "weibull_failed_only": "Weibull, failed engines only",
    "weibull_censored": "Weibull, with running engines (censored)",
    "gbm_imputed": "GBM + survival-imputed labels",
    "gbm_imputed_failfit": "GBM + imputed labels (Weibull fit on failures only)",
}


def _pct(x):
    return "n/a" if x is None else f"{100 * x:.0f}%"


def _f(x, d=1):
    return "n/a" if x is None else f"{x:.{d}f}"


def render(res: dict) -> str:
    L = []
    A = L.append
    A("# Uncertainty and survival analysis: generated by `uq_survival.py`\n")
    A("Two additions to the RUL model, both aimed at questions the point prediction "
      "cannot answer:\n")
    A("- **Conformal prediction:** how wrong can \"23 cycles left\" be, with a "
      "guarantee attached? And does alarming on the safe end of that range help?")
    A("- **Survival analysis:** a real fleet has few failures and many engines still "
      "running. Can the running engines be used instead of thrown away?\n")
    if res.get("quick"):
        A("> **Quick run** (FD001, one seed). Run `python uq_survival.py` for the full "
          "numbers.\n")

    # ------------------------------------------------------------- Part A
    A("## Part A: conformal lower bounds\n")
    A("A one-sided **90% lower bound** on remaining life: \"at least X cycles left\", "
      "true 90% of the time. One-sided because over-predicting life is the dangerous "
      "error. Calibrated with 5-fold cross-conformal (CV+) grouped by engine, so every "
      "training engine contributes an out-of-fold residual. Scored on 20 held-out "
      "engines per sub-dataset (every cycle) and on the official test set (one point "
      "per engine).\n")
    A("| sub-dataset | method | coverage, held-out engines | coverage when true RUL < 25 | "
      "coverage, official test set | average margin (cycles) |")
    A("|---|---|---|---|---|---|")
    label = {"quantile_gbm_raw": "quantile GBM, not calibrated", "split": "split conformal",
             "mondrian": "Mondrian (per band)", "cqr": "CQR (conformal quantile)"}
    for c in res["conformal"]:
        for k in ("quantile_gbm_raw", "split", "mondrian", "cqr"):
            h, t = c["coverage"][k]["holdout"], c["coverage"][k]["test"]
            A(f"| {c['fd']} | {label[k]} | {_pct(h['coverage'])} | {_pct(h['true_rul_0_25'])} | "
              f"{_pct(t['coverage'])} | {_f(h['mean_margin'])} |")
    A("")

    def mean_cov(kind, split, key="coverage"):
        v = [c["coverage"][kind][split][key] for c in res["conformal"]
             if c["coverage"][kind][split][key] is not None]
        return float(np.mean(v)) if v else None

    raw = mean_cov("quantile_gbm_raw", "holdout")
    A(f"**Reading it.** Averaged over sub-datasets, the calibrated bounds cover "
      f"{_pct(mean_cov('split', 'holdout'))} (split), {_pct(mean_cov('mondrian', 'holdout'))} "
      f"(Mondrian) and {_pct(mean_cov('cqr', 'holdout'))} (CQR) of held-out cycles against "
      f"a 90% target. The uncalibrated quantile model, which was *trained* to be a 10th "
      f"percentile, covers only {_pct(raw)}: the calibration step is what makes the "
      f"number true.\n")
    A(f"**Near failure (true RUL < 25), where the alarm decision is made**, the three "
      f"differ. Split conformal over-covers "
      f"({_pct(mean_cov('split', 'holdout', 'true_rul_0_25'))}): one correction sized for the "
      f"noisy healthy region is too wide where the model is sharp. Mondrian, calibrated per "
      f"band of *predicted* RUL, comes in under target "
      f"({_pct(mean_cov('mondrian', 'holdout', 'true_rul_0_25'))}, and "
      f"{_pct(res['conformal'][-1]['coverage']['mondrian']['holdout']['true_rul_0_25'])} on "
      f"{res['conformal'][-1]['fd']}), because an engine the model wrongly thinks is healthy "
      f"sits in the wrong band. **CQR holds up best here "
      f"({_pct(mean_cov('cqr', 'holdout', 'true_rul_0_25'))})**, because its width comes from "
      f"the sensors, not from the prediction.\n")
    A(f"**The official test set comes in lower** "
      f"({_pct(mean_cov('split', 'test'))} / {_pct(mean_cov('mondrian', 'test'))} / "
      f"{_pct(mean_cov('cqr', 'test'))}). That is a limit of what the method "
      f"promises: the guarantee holds for points drawn the same way as "
      f"the calibration points (every cycle of an engine's life). The test set takes "
      f"one point per engine at a random cut-off, which over-samples mid-life. Mid-life (the "
      f"knee where wear starts) is where coverage is lowest on the held-out engines too "
      f"(true RUL 50-125: {_pct(mean_cov('cqr', 'holdout', 'true_rul_50_125'))} for CQR), so "
      f"that is the likely reason. A "
      f"guarantee is only as good as the match between calibration and use.\n")

    # alarm comparison
    al = res["alarm"]
    A("### Does alarming on the lower bound help?\n")
    A("`split` and `Mondrian` compute the bound from the point prediction alone, so "
      "alarming on the bound is identical to moving the threshold on the prediction. "
      "Only **CQR** can alarm earlier on an *unusual* engine than on a typical one with "
      "the same prediction. The fair test compares policies at the **same average "
      "warning** (the same amount of engine life thrown away) and asks which one "
      "protects the worst engines better.\n")
    A(f"Pooled over {al['n_units']} held-out engines, persistence k and threshold "
      f"searched per signal:\n")
    A("| average warning | point prediction: engines missed / worst engine | "
      "CQR lower bound: engines missed / worst engine |")
    A("|---|---|---|")
    for row in al["matched"]:
        p, q = row["point"], row["cqr"]
        if not p or not q:
            continue
        A(f"| ~{row['target_mean_lead']} cycles | {p['missed']} / {p['lead_min']:.0f} cycles | "
          f"{q['missed']} / {q['lead_min']:.0f} cycles |")
    A("")
    A("*Missed = less than 10 cycles of warning, or none. Worst engine = the least "
      "warning any single engine got.*\n")
    z = al.get("zero_miss")
    if z:
        sv = z["saving_point_minus_cqr"]
        A(f"**The safety question, asked directly: how much average warning does each "
          f"signal need before no engine is missed?** The point prediction needs "
          f"**{z['point']:.1f} cycles**; the CQR lower bound needs **{z['cqr']:.1f}**. "
          f"Same safety, **{sv['estimate']:.1f} fewer cycles of engine life thrown away "
          f"per engine** (bootstrap over engines: 95% CI {sv['lo']:.1f} to {sv['hi']:.1f}, "
          f"positive in {100 * sv['frac_positive']:.1f}% of resamples).\n")
        A("Why: the point prediction is confidently wrong on a few unusual engines. To "
          "catch those, a plain threshold has to fire early on *every* engine. CQR widens "
          "the safety range only where the sensors look unusual, so it can fire early on "
          "those engines and late on the rest.\n")
        o = z["out_of_sample"]
        A(f"**Out of sample.** The numbers above pick each policy on the same engines they "
          f"score. Choosing the policy on a random half and scoring it on the other half "
          f"(200 splits): point prediction misses {o['point']['mean_missed_of_40']:.2f} of "
          f"40 engines on average with {o['point']['mean_warning']:.1f} cycles of average "
          f"warning; CQR misses {o['cqr']['mean_missed_of_40']:.2f} with "
          f"{o['cqr']['mean_warning']:.1f}. The saving survives: similar misses, "
          f"{o['point']['mean_warning'] - o['cqr']['mean_warning']:.1f} fewer cycles "
          f"thrown away. **But neither reaches zero misses on engines it has not seen** "
          f"({100 * o['point']['frac_splits_with_a_miss']:.0f}% / "
          f"{100 * o['cqr']['frac_splits_with_a_miss']:.0f}% of splits miss at least one). "
          f"A policy tuned to \"no misses\" on 40 engines is not a no-miss policy; a real "
          f"safety case needs a margin on top.\n")
    boot = al.get("bootstrap_cqr_minus_point_p05") or {}
    if boot:
        parts = [f"{b['median']:+.1f} cycles at ~{t} [95% CI {b['lo']:+.1f}, {b['hi']:+.1f}]"
                 for t, b in boot.items()]
        A("On the *worst 5%* of engines (rather than the worst one) the gain is smaller "
          "and not significant: CQR minus point = " + "; ".join(parts) + ". The benefit "
          "is concentrated in the few engines the point model gets badly wrong, which "
          "are exactly the ones that decide a safety case.\n")
    tp, tq = al["tuned"]["point"], al["tuned"]["cqr"]
    A(f"Under the project's default cost model, the best point-prediction policy costs "
      f"{tp['cost_per_unit']:.2f} per engine (RUL<{tp['threshold']:.0f}, k={tp['k']}, "
      f"{tp['nuisance_per_unit']:.2f} false alarms per engine) and the best CQR policy "
      f"{tq['cost_per_unit']:.2f} (bound<{tq['threshold']:.0f}, k={tq['k']}, "
      f"{tq['nuisance_per_unit']:.2f} false alarms per engine).\n")

    # ------------------------------------------------------------- Part B
    A("## Part B: survival analysis on a censored fleet\n")
    A("Each training fleet is cut down so only *n* engines are observed to failure; "
      "every other engine is still running, observed up to a random point in its life "
      "(right-censored). Everything, including the sensor normalisation, is refitted on "
      "what that fleet has actually seen. Scored on the official test set.\n")
    A("Six ways to use that fleet:\n")
    A("1. **GBM, drop running engines.** What the rest of this repo does: no label, no row.")
    A("2. **GBM, treat running engines as failed.** The trap: pretends every engine "
      "failed the day observation stopped.")
    A("3. **Weibull, failed engines only.** A survival model without the extra data "
      "(the control).")
    A("4. **Weibull, with running engines.** Weibull accelerated-failure-time model on "
      "landmark data, using the censoring properly.")
    A("5. **GBM + survival-imputed labels.** Running engines get the label the survival "
      "model expects *given that they survived at least this long*: "
      "E[min(RUL, 125) | still running, sensors]. The GBM trains on real labels plus these.")
    A("6. **Same, Weibull fit on failures only.** Separates the value of the censoring "
      "logic from the particular fitted curve.\n")

    summ = res["survival_summary"]
    A("Test RMSE, mean ± sd over seeds (lower is better):\n")
    head = "| sub-dataset | failures seen | " + " | ".join(NAMES[m] for m in NAMES) + " |"
    A(head)
    A("|" + "---|" * (2 + len(NAMES)))
    for r in summ:
        best = min(NAMES, key=lambda m: r[m]["rmse_mean"])
        cells = []
        for m in NAMES:
            s = f"{r[m]['rmse_mean']:.1f} ± {r[m]['rmse_sd']:.1f}"
            cells.append(f"**{s}**" if m == best else s)
        A(f"| {r['fd']} | {r['n_failures']} of {r['n_failures'] + r['n_censored']} | "
          + " | ".join(cells) + " |")
    A("")
    A("Reference with **every** engine run to failure (the luxury C-MAPSS normally "
      "gives): " + ", ".join(
          f"{s['fd']} GBM {s['reference']['gbm_full']['rmse']:.1f} / Weibull "
          f"{s['reference']['weibull_full']['rmse']:.1f}" for s in res["survival"]) + ".\n")

    def mean_over(m, n):
        v = [r[m]["rmse_mean"] for r in summ if r["n_failures"] == n]
        return float(np.mean(v))

    ns = sorted({r["n_failures"] for r in summ})
    A("Averaged over sub-datasets:\n")
    A("| failures seen | " + " | ".join(NAMES[m] for m in NAMES) + " |")
    A("|" + "---|" * (1 + len(NAMES)))
    for n in ns:
        A(f"| {n} | " + " | ".join(f"{mean_over(m, n):.1f}" for m in NAMES) + " |")
    A("")

    A("**What it shows.**\n")
    A(f"- **Treating running engines as failed is the worst option at every fleet size** "
      f"({', '.join(f'{mean_over('gbm_naive', n):.1f}' for n in ns)} RMSE). It teaches the "
      f"model that healthy engines are about to die. More data used wrongly is worse "
      f"than less data.")
    ff_wins = [n for n in ns if mean_over("gbm_imputed_failfit", n) < mean_over("gbm_failed_only", n)]
    gains = ", ".join(f"{mean_over('gbm_failed_only', n) - mean_over('gbm_imputed_failfit', n):+.1f} "
                      f"at {n}" for n in ns)
    cells = [(r["fd"], r["n_failures"]) for r in summ]
    n_best = sum(1 for r in summ if min(NAMES, key=lambda m: r[m]["rmse_mean"]) == "gbm_imputed_failfit")
    n_beats_drop = sum(1 for r in summ
                       if r["gbm_imputed_failfit"]["rmse_mean"] < r["gbm_failed_only"]["rmse_mean"])
    sd_drop = np.mean([r["gbm_failed_only"]["rmse_sd"] for r in summ])
    sd_ff = np.mean([r["gbm_imputed_failfit"]["rmse_sd"] for r in summ])
    A(f"- **The method that works: a Weibull fitted on the failed engines, used to fill in "
      f"labels for the running ones** (\"given it has survived this long, how long is "
      f"left?\"), then a GBM trained on all of it. Averaged over sub-datasets it beats "
      f"dropping the running engines at {len(ff_wins)} of {len(ns)} fleet sizes "
      f"(RMSE reduction: {gains} failures seen; negative means worse). It is the single best method in "
      f"{n_best} of {len(cells)} cells and beats dropping in {n_beats_drop} of "
      f"{len(cells)}. The gains are modest (1-2 RMSE when failures are scarce, none at "
      f"20), but it is also **steadier**: seed-to-seed spread {sd_ff:.1f} vs {sd_drop:.1f} "
      f"RMSE for dropping. With 5 failures, which 5 you happened to see matters a lot "
      f"when the other engines are thrown away, and much less when they are used.")
    A("- **Why the failures-only fit, not the one that also saw the running engines.** "
      "The running engines still contribute: the label each one gets is conditioned on "
      "how long it has already survived, which is the censoring information. What they "
      "should not do is shape the fitted life curve, for the reason in the next point.")
    wc = [n for n in ns if mean_over("weibull_censored", n) < mean_over("weibull_failed_only", n)]
    A(f"- **The Weibull on its own gets worse, not better, when the running engines are "
      f"added** (better at {len(wc)} of {len(ns)} fleet sizes). The model is the "
      f"bottleneck: log-life linear in the sensors, one shape for every engine. Running "
      f"engines are mostly early-life rows and outnumber the failures, so they pull the "
      f"straight line toward the healthy region and it becomes optimistic late in life. "
      f"Letting the shape vary with the sensors (ancillary regression) was tried and "
      f"did not fix it. The survival model is useful here as a *label generator* for "
      f"the GBM, not as the predictor.")
    A("- **C-index** (does the model rank which engine fails first correctly; 0.5 is "
      "chance): " + "; ".join(
          f"{n} failures: GBM-drop {np.mean([r['gbm_failed_only']['cindex_mean'] for r in summ if r['n_failures'] == n]):.3f}, "
          f"imputed {np.mean([r['gbm_imputed_failfit']['cindex_mean'] for r in summ if r['n_failures'] == n]):.3f}"
          for n in ns) + ".\n")
    A("**Limits.** Censoring here is random (each running engine is cut at a uniform "
      "point in its life). Real censoring is not random: engines that reach failure "
      "are the ones maintenance missed. `complete.py` stage 8 models that bias for the "
      "drop-the-running-engines baseline; it is not re-run here. Three seeds per cell "
      "is enough to see the direction, not to rank close methods.\n")
    A(f"Wall time: {res.get('wall_seconds', 0) / 60:.1f} min.")
    return "\n".join(L) + "\n"
